# Generated by Django 4.2.1 on 2023-05-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_signimages_uploaded_at_alter_signimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signimages',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
